import localFont from "next/font/local";
import '../../public/template/css/bootstrap.min.css'
import '../../public/template/css/responsive.css'
import '../../public/template/css/style.min.css'
import "./globals.css";
import DefaultHeader from "@/components/layout/DefaultHeader";
import DefaultFooter from "@/components/layout/DefaultFooter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en" className="select-none">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ overflowX: 'hidden' }}
      >
        {children}
      </body>
    </html>
  );
}
